import Navbar from './components/navbar/Navbar';
import './globals.css';
import { Source_Sans_Pro } from 'next/font/google';

// If loading a variable font, you don't need to specify the font weight
const ssp = Source_Sans_Pro({
  subsets: ['latin'],
  weight: '300',
});
const headingFont = ssp.className;

export const metadata = {
  title: 'A+ Pathshala',
  description: 'Generated by create next app',
  icons: {
    icon: '/icon.svg',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ssp.className}>
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
